/**
 * 👑 King RANUX PRO – User Configuration
 * Users are allowed to edit ONLY this file
 */

module.exports = {

  // 🔐 WhatsApp Session ID
  SESSION_ID: process.env.SESSION_ID || "𝐊𝐢𝐧𝐠 𝐑𝐀𝐍𝐔𝐗 ᴾʳᵒ ~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0V5Mm04ajR2Y3lEZ2pnd09zb3VsOGRqdG5ZUWM3QlpXK3F1V2RUeEdFZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR2I4Wk1XaU5BZzV5NVpLbmp1U0VqYThpajFUUmVRZk1EUHhRY1lJeWxpdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnSjN3cXBSMWdUVTJhQlRldkdFTkJRbnVUTFBGdTR6YmN6WEdJR2hKeDJ3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJSSE16WW56T0JiTFRpcXZmd2NBMEZwaWlPc2I4L0x0eE9Ka3FJMEJKRUhrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1GTXVjWjdEUk5Wc3hCY2ZhaGhOam5xUVU5SUJheUZhdzFMczhhNW9pbDQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlJjWTFQditDanppRTMvRk96ODFBZlhtelZwQUoxWEpVSXBTS0g5Rnc2RFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUpNSHZIMUVscDNTS2RLcVNJUVRJRzhod0RtQnArWDRzVVk1ZVNjQ0FWOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMnF3aHluWXFjbUJKK2FDSi9tM3hPU0VIZGlqQis1TGZKZHBVeDBKNVZCbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFKTGl6ZnFXaERLNk0zWFRMeUJTS0FhYlhOdVNSZ3BFcFROSHJLSDMvL3lwMGJoTTdoR3drdFQxQlFPWmVGNEJXNjJzSGJHN2JFTjdHLzdpMXltM2dBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTk5LCJhZHZTZWNyZXRLZXkiOiJ4TWkxcyt6YnBWdWxNOVM3aTZNbmEyWUZEU2g0OU4zQXN4dk5ydmwwK0hjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxODUyNzg3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBQzY1MkY1RkE0REQzMkJENUM3MDA1RkFCMzE3MEM3MCIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzY5OTQxMjU2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDc0MTg1Mjc4N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQUMxNEYzQzgzN0IyQjNCMjk3NzNCRDE5NjVCODFEODgiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2OTk0MTI1Nn0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NDE4NTI3ODdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkFDNUYyQTUzNzg1MjlCMUM3NDI5RDc1Nzg3RkJGQkVBIiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3Njk5NDEyNTZ9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxODUyNzg3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBQzM3QTQ1ODVGQkI0QUZFRUVDMUM2Q0UzMkM0QTczNiIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzY5OTQxMjU3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDc0MTg1Mjc4N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQUNFMDQ4Q0JGMDRERjIzQTk2MERERjJEOTBEN0ZFQTUiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2OTk0MTI2M31dLCJuZXh0UHJlS2V5SWQiOjgxMywiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjgxMywiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI4M1hMR1A1RyIsIm1lIjp7ImlkIjoiOTQ3NDE4NTI3ODc6MzFAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI1NTY1MDQ0NDkwMjU2NjozMUBsaWQiLCJuYW1lIjoiUmFuc2FyYSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSnFIZzM0UWc5TDh5d1lZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUzFzUk45azlMaTJxTFNMSTFEOStFc0t5UDRiUDU1R1BONGdMNEtxU1BTUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiWlVqK0FiSVBoOGxZTEl1OVhtSkVETGsrRG84NlRuaERneUJ0RlluSzRjOGdSQlZzWlZHNlZUSTI5N3RqWlpmQ3drZnptajJDZ1Y2eFg4ZzdndVlNQmc9PSIsImRldmljZVNpZ25hdHVyZSI6IkwwK3JqRW1RRGFoRzl4emdOc0EraEUyUkZweE5OczczYWZsT1d1SDhqOHlTcHVVeUJhd2NtRmwwamtwdGJmNlF0QVV0M0JGVjRoZWNkZmZmZkVKaWdRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiNTU2NTA0NDQ5MDI1NjY6MzFAbGlkIiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlV0YkVUZlpQUzR0cWkwaXlOUS9maExDc2orR3orZVJqemVJQytDcWtqMGsifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlEUWdDIn0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc2OTk0MTI1NCwibGFzdFByb3BIYXNoIjoiM1I5WjM5IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFMajgifQ==",

  // ===============================
  // 🤖 BOT MODE SYSTEM
  // public  = groups + inbox
  // group   = groups only
  // inbox   = inbox only
  // private = owner + sudo only
  // ===============================
  MODE: process.env.MODE || "public",

  // ===============================
  // 📌 STATUS AUTOMATION
  // ===============================
  AUTO_STATUS_SEEN: true,
  AUTO_STATUS_REACT: false,
  AUTO_STATUS_FORWARD: false,

  // ===============================
  // 🛡️ ANTI DELETE
  // ===============================
  ANTI_DELETE: true,

  // ===============================
  // ⚙️ GENERAL
  // ===============================
  PREFIX: process.env.PREFIX || ".",

  // ===============================
  // 🎬 MOVIE PLUGIN FOOTER
  // ===============================
  MOVIE_FOOTER_TEXT: "𝓜𝓡. 𝓡𝓪𝓷𝓼𝓪𝓻𝓪 𝓓𝓮𝓿𝓷𝓪𝓽𝓱",
  
};
