/**
 * 👑 King RANUX PRO – User Configuration
 * Users are allowed to edit ONLY this file
 */

module.exports = {

  // 🔐 WhatsApp Session ID
  SESSION_ID: process.env.SESSION_ID || "𝐊𝐢𝐧𝐠 𝐑𝐀𝐍𝐔𝐗 ᴾʳᵒ ~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUgvL0NzMWoydmtkV1YxK0JGd3lkSXFnbENqamZqdVlqVWtRR1BXRkJXST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiak1LQWJzNFpja0dMdkdrRWVvaFA3UUpPVXR6MStWU0lTczdJODZ1M2kyaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnS2E5RVQwaXRYTXFpMmNCVzlhcDBwRFhEZjlReXdBcWphcTFRUUhRaFc0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3dXEwb0JCSEIzREdyTVJYd3F1cEZGdFFZUEkwdW1MdWd2aWE2UXFVNGwwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IllLWERXV05XUEI5aVRiNDBPa01LZmFleVZnQTZlVmNKZDJzQ3FHdFNMa009In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVSL3VQVW1wSW5obytTZFdyRVp2NlJURE5pcTNXU3BHNHVjRk1oOUh2RVk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0tzNnZDcHBMWW8xbFNESjVnU1hncmhTTUcvRGM3alFlZzcrcDd6RXgyQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUxUSlJQOFlheDV3TzZiajNNOEtET3ZtcnM1RWxwTmVJRmFkNE5sUWF3cz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdSRC9HdzJBNUNDOTRhdU1PMDJHUjNWSGdyYzF5NE1tdjludlYvS0EzRUVFKzlRUVVsQUN3VFJIOEdEVHpDcWZ3cUFuRzlDT3kvMW05TVhDOFJqYURnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE3LCJhZHZTZWNyZXRLZXkiOiJhWjEwaU42UkFXdG1Qc3VRVE54OC9UVk1KUTlVeExuQ2hlejAzRnl6c0hFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxODUyNzg3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBQzJERkJCRUU1NTQ5NkE5NDgwQkIzMzM4NDJFREVBNCIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzcwNTE5OTM4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDc0MTg1Mjc4N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQUMxQzZDOTE0QUYwMUJCQUNDQTYxRDE1NTFDMzlFMUMiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3MDUxOTkzOH0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NDE4NTI3ODdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkFDMURFOERCQzM0RTk3QTdEQTU1NkFDNjMxMUYxMDdCIiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzA1MTk5Mzh9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxODUyNzg3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBQzVCMzNDM0E5QUE1N0I3MDM5Rjc2NzM5Q0JCNTc4NCIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzcwNTE5OTM5fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDc0MTg1Mjc4N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQUM2MTI2OTFGMjRBMEE2MUUzRDM4MTNBRTZFNTJBOTUiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3MDUxOTk0NX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NDE4NTI3ODdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkFDMkMyMzREQUQ5MzkyODVGNTI3RkYyQzMxQjg1NDAzIiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzA1MTk5NDZ9XSwibmV4dFByZUtleUlkIjo4MTMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo4MTMsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiTFZKSDg3SkgiLCJtZSI6eyJpZCI6Ijk0NzQxODUyNzg3OjM0QHMud2hhdHNhcHAubmV0IiwibGlkIjoiNTU2NTA0NDQ5MDI1NjY6MzRAbGlkIiwibmFtZSI6ImtpbmcifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0p5SGczNFEvZnFmekFZWUFTQUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlMxc1JOOWs5TGkycUxTTEkxRDkrRXNLeVA0YlA1NUdQTjRnTDRLcVNQU1E9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImdCUTJBNEF6VDA1Skc1QVQ3V21sZWpnTkZlbVgvRnh1S0pZaVdCWXByZStKUVpGbVNISDh5U2RUbjFBZzFzK3dzVlBFWDlGaTl6VjdPK1krWTV6OENnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIwdEZvQVZZeENZSUVQcllPWTJGNlI0M2F3dk0xRURxKzRSU1Y2d3NjVnhhUGh6KzR3QXpPVWZXUm5tcFhsZkhDYlIyS21RZUZQYW1pa1FRVDA2V3hDQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjU1NjUwNDQ0OTAyNTY2OjM0QGxpZCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJVdGJFVGZaUFM0dHFpMGl5TlEvZmhMQ3NqK0d6K2VSanplSUMrQ3FrajBrIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJRFFnQyJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NzA1MTk5MzcsImxhc3RQcm9wSGFzaCI6IjNSOVozOSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTnFkIn0=",
  // ===============================
  // 🤖 BOT MODE SYSTEM
  // public  = groups + inbox
  // group   = groups only
  // inbox   = inbox only
  // private = owner + sudo only
  // ===============================
  MODE: process.env.MODE || "private",

  // ===============================
  // 📌 STATUS AUTOMATION
  // ===============================
  AUTO_STATUS_SEEN: true,
  AUTO_STATUS_REACT: false,
  AUTO_STATUS_FORWARD: false,

  // ===============================
  // 🛡️ ANTI DELETE
  // ===============================
  ANTI_DELETE: true,

  // ===============================
  // ⚙️ GENERAL
  // ===============================
  PREFIX: process.env.PREFIX || ".",

  // ===============================
  // 🎬 MOVIE PLUGIN FOOTER
  // ===============================
  MOVIE_FOOTER_TEXT: "𝓜𝓡. 𝓡𝓪𝓷𝓼𝓪𝓻𝓪 𝓓𝓮𝓿𝓷𝓪𝓽𝓱",
  
};
